#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 22 13:01:03 2016

@author: juliannecrea
"""

import pymysql
import json
import os
import tweepy
from db_connect import *

def twitter_connect():
    API_KEY = 'bOondRoF63msjOZn2MBltACwk'
    API_SECRET = 'bQSHowUX8L2oQNvD3xzIpQzqhkdvrd7JCb20gC5iwn2KTSByjV'
    TOKEN_KEY = '728312577080451072-8PeNy9HzQuSjgm7JZsUt3obZ1fpZS3c'
    TOKEN_SECRET = 'Rmk3FcMEO1tCEjTgedGtRMCGjzvQnWrP182ulaY1hmNVB'
    auth = tweepy.OAuthHandler(API_KEY, API_SECRET)
    auth.set_access_token(TOKEN_KEY, TOKEN_SECRET)
    api = tweepy.API(auth)
    return api

def class_search_insert(api, unique):

    try:
        connection = create_connection()
        dbcursor = connection.cursor()
        stmt = "SELECT name FROM Class WHERE unique_number = %s"
        run_prepared_stmt(dbcursor, stmt, (unique))
        keyword = dbcursor.fetchone()[0]
        apicursor = tweepy.Cursor(api.search, q=keyword, lang='en')

        for item in apicursor.pages().next():
            stmt = "INSERT into ClassTweet (unique_num, tweet) VALUES (%s, %s)"
            run_prepared_stmt(dbcursor, stmt, (unique, json.dumps(item._json)))
        do_commit(connection)
    except pymysql.Error as e:
        print ("Error: " + e.args[0])

def update_all_JS(path, value):

    try:
        connection = create_connection()
        cursor = connection.cursor()

        stmt = "UPDATE ClassTweet SET tweet = JSON_INSERT(tweet, %s, %s)"
        run_prepared_stmt(cursor, stmt, (path, value))
        do_commit(connection)
    except pymysql.Error as e:
        print ("Error: " + e.args[1])

def search_keyword(key):
    try:
        connection = create_connection()
        cursor = connection.cursor()

        stmt = "SELECT tweet->\"$.text\" from ClassTweet where tweet->\"$.text\" LIKE %s"
        run_prepared_stmt(cursor, stmt, ("%"+key+"%"))

        for row in cursor:
            print (row[0])
    except pymysql.Error as e:
        print ("Error: " +e.args[1])

def search_path(path):
    try:
        connection = create_connection()
        cursor = connection.cursor()

        stmt = "SELECT tweet->%s from ClassTweet where JSON_CONTAINS_PATH(tweet, 'one', %s) = 1"
        run_prepared_stmt(cursor, stmt, (path, path))

        for row in cursor:
            print (row[0])
    except pymysql.Error as e:
        print ("Error: " +e.args[0])

if __name__ == "__main__":
    api = twitter_connect()
    # class_search_insert(api, 100)

    search_keyword("ebola")
    print ("===================")
    search_path("$.entities.user_mentions[0].name")
    #print "==================="
    update_all_JS("$.add", "true")